### ISSUE TITLE
Select by id is throwing java.sql.SQLSyntaxErrorException

### ISSUE THREAD

**Issue by mezaleo** [hodrigohamalho/fis-rest#1]
By calling /api/orders/order/{id} operation, the service is throwing java.sql.SQLSyntaxErrorException.

[stacktrace.log](https://github.com/hodrigohamalho/fis-rest/files/3962126/stacktrace.log)

**Comment by hodrigohamalho** [comment]
Hi @mezaleo, thanks for reporting it.

Do you mind to send a PR? 

Best

**Comment by mezaleo** [comment]
Hi @hodrigohamalho 

PR done!

Kind regards

**Comment by hodrigohamalho** [comment]
Thanks!
